<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use App\Country;

class CountryTableSeeder extends Seeder {

    public function run()
    {
        DB::table('countries')->delete();

		Country::create(['calling_code' => '93', 'code' => 'AF', 'name' => 'Afghanistan']);
		Country::create(['calling_code' => '358', 'code' => 'AX', 'name' => 'Åland Islands']);
		Country::create(['calling_code' => '355', 'code' => 'AL', 'name' => 'Albania']);
		Country::create(['calling_code' => '213', 'code' => 'DZ', 'name' => 'Algeria']);
		Country::create(['calling_code' => '1', 'code' => 'AS', 'name' => 'American Samoa']);
		Country::create(['calling_code' => '376', 'code' => 'AD', 'name' => 'Andorra']);
		Country::create(['calling_code' => '244', 'code' => 'AO', 'name' => 'Angola']);
		Country::create(['calling_code' => '1', 'code' => 'AI', 'name' => 'Anguilla']);
		Country::create(['calling_code' => '672', 'code' => 'AQ', 'name' => 'Antarctica']);
		Country::create(['calling_code' => '1', 'code' => 'AG', 'name' => 'Antigua and Barbuda']);
		Country::create(['calling_code' => '54', 'code' => 'AR', 'name' => 'Argentina']);
		Country::create(['calling_code' => '374', 'code' => 'AM', 'name' => 'Armenia']);
		Country::create(['calling_code' => '297', 'code' => 'AW', 'name' => 'Aruba']);
		Country::create(['calling_code' => '61', 'code' => 'AU', 'name' => 'Australia']);
		Country::create(['calling_code' => '43', 'code' => 'AT', 'name' => 'Austria']);
		Country::create(['calling_code' => '994', 'code' => 'AZ', 'name' => 'Azerbaijan']);
		Country::create(['calling_code' => '1', 'code' => 'BS', 'name' => 'Bahamas']);
		Country::create(['calling_code' => '973', 'code' => 'BH', 'name' => 'Bahrain']);
		Country::create(['calling_code' => '880', 'code' => 'BD', 'name' => 'Bangladesh']);
		Country::create(['calling_code' => '1', 'code' => 'BB', 'name' => 'Barbados']);
		Country::create(['calling_code' => '375', 'code' => 'BY', 'name' => 'Belarus']);
		Country::create(['calling_code' => '32', 'code' => 'BE', 'name' => 'Belgium']);
		Country::create(['calling_code' => '501', 'code' => 'BZ', 'name' => 'Belize']);
		Country::create(['calling_code' => '229', 'code' => 'BJ', 'name' => 'Benin']);
		Country::create(['calling_code' => '1', 'code' => 'BM', 'name' => 'Bermuda']);
		Country::create(['calling_code' => '975', 'code' => 'BT', 'name' => 'Bhutan']);
		Country::create(['calling_code' => '591', 'code' => 'BO', 'name' => 'Bolivia, Plurinational State of']);
		Country::create(['calling_code' => '387', 'code' => 'BA', 'name' => 'Bosnia and Herzegovina']);
		Country::create(['calling_code' => '267', 'code' => 'BW', 'name' => 'Botswana']);
		Country::create(['calling_code' => '55', 'code' => 'BR', 'name' => 'Brazil']);
		Country::create(['calling_code' => '246', 'code' => 'IO', 'name' => 'British Indian Ocean Territory']);
		Country::create(['calling_code' => '673', 'code' => 'BN', 'name' => 'Brunei Darussalam']);
		Country::create(['calling_code' => '359', 'code' => 'BG', 'name' => 'Bulgaria']);
		Country::create(['calling_code' => '226', 'code' => 'BF', 'name' => 'Burkina Faso']);
		Country::create(['calling_code' => '257', 'code' => 'BI', 'name' => 'Burundi']);
		Country::create(['calling_code' => '855', 'code' => 'KH', 'name' => 'Cambodia']);
		Country::create(['calling_code' => '237', 'code' => 'CM', 'name' => 'Cameroon']);
		Country::create(['calling_code' => '1', 'code' => 'CA', 'name' => 'Canada']);
		Country::create(['calling_code' => '238', 'code' => 'CV', 'name' => 'Cape Verde']);
		Country::create(['calling_code' => '1', 'code' => 'KY', 'name' => 'Cayman Islands']);
		Country::create(['calling_code' => '236', 'code' => 'CF', 'name' => 'Central African Republic']);
		Country::create(['calling_code' => '235', 'code' => 'TD', 'name' => 'Chad']);
		Country::create(['calling_code' => '56', 'code' => 'CL', 'name' => 'Chile']);
		Country::create(['calling_code' => '86', 'code' => 'CN', 'name' => 'China']);
		Country::create(['calling_code' => '61', 'code' => 'CX', 'name' => 'Christmas Island']);
		Country::create(['calling_code' => '61', 'code' => 'CC', 'name' => 'Cocos (Keeling) Islands']);
		Country::create(['calling_code' => '57', 'code' => 'CO', 'name' => 'Colombia']);
		Country::create(['calling_code' => '269', 'code' => 'KM', 'name' => 'Comoros']);
		Country::create(['calling_code' => '242', 'code' => 'CG', 'name' => 'Congo']);
		Country::create(['calling_code' => '243', 'code' => 'CD', 'name' => 'Congo, the Democratic Republic of the']);
		Country::create(['calling_code' => '682', 'code' => 'CK', 'name' => 'Cook Islands']);
		Country::create(['calling_code' => '506', 'code' => 'CR', 'name' => 'Costa Rica']);
		Country::create(['calling_code' => '225', 'code' => 'CI', 'name' => 'Côte d\'Ivoire']);
		Country::create(['calling_code' => '385', 'code' => 'HR', 'name' => 'Croatia']);
		Country::create(['calling_code' => '53', 'code' => 'CU', 'name' => 'Cuba']);
		Country::create(['calling_code' => '357', 'code' => 'CY', 'name' => 'Cyprus']);
		Country::create(['calling_code' => '420', 'code' => 'CZ', 'name' => 'Czech Republic']);
		Country::create(['calling_code' => '45', 'code' => 'DK', 'name' => 'Denmark']);
		Country::create(['calling_code' => '253', 'code' => 'DJ', 'name' => 'Djibouti']);
		Country::create(['calling_code' => '1', 'code' => 'DM', 'name' => 'Dominica']);
		Country::create(['calling_code' => '1', 'code' => 'DO', 'name' => 'Dominican Republic']);
		Country::create(['calling_code' => '593', 'code' => 'EC', 'name' => 'Ecuador']);
		Country::create(['calling_code' => '20', 'code' => 'EG', 'name' => 'Egypt']);
		Country::create(['calling_code' => '503', 'code' => 'SV', 'name' => 'El Salvador']);
		Country::create(['calling_code' => '240', 'code' => 'GQ', 'name' => 'Equatorial Guinea']);
		Country::create(['calling_code' => '291', 'code' => 'ER', 'name' => 'Eritrea']);
		Country::create(['calling_code' => '372', 'code' => 'EE', 'name' => 'Estonia']);
		Country::create(['calling_code' => '251', 'code' => 'ET', 'name' => 'Ethiopia']);
		Country::create(['calling_code' => '500', 'code' => 'FK', 'name' => 'Falkland Islands (Malvinas)']);
		Country::create(['calling_code' => '298', 'code' => 'FO', 'name' => 'Faroe Islands']);
		Country::create(['calling_code' => '679', 'code' => 'FJ', 'name' => 'Fiji']);
		Country::create(['calling_code' => '358', 'code' => 'FI', 'name' => 'Finland']);
		Country::create(['calling_code' => '33', 'code' => 'FR', 'name' => 'France']);
		Country::create(['calling_code' => '594', 'code' => 'GF', 'name' => 'French Guiana']);
		Country::create(['calling_code' => '689', 'code' => 'PF', 'name' => 'French Polynesia']);
		Country::create(['calling_code' => '262', 'code' => 'TF', 'name' => 'French Southern Territories']);
		Country::create(['calling_code' => '241', 'code' => 'GA', 'name' => 'Gabon']);
		Country::create(['calling_code' => '220', 'code' => 'GM', 'name' => 'Gambia']);
		Country::create(['calling_code' => '995', 'code' => 'GE', 'name' => 'Georgia']);
		Country::create(['calling_code' => '49', 'code' => 'DE', 'name' => 'Germany']);
		Country::create(['calling_code' => '233', 'code' => 'GH', 'name' => 'Ghana']);
		Country::create(['calling_code' => '350', 'code' => 'GI', 'name' => 'Gibraltar']);
		Country::create(['calling_code' => '30', 'code' => 'GR', 'name' => 'Greece']);
		Country::create(['calling_code' => '299', 'code' => 'GL', 'name' => 'Greenland']);
		Country::create(['calling_code' => '1', 'code' => 'GD', 'name' => 'Grenada']);
		Country::create(['calling_code' => '590', 'code' => 'GP', 'name' => 'Guadeloupe']);
		Country::create(['calling_code' => '1', 'code' => 'GU', 'name' => 'Guam']);
		Country::create(['calling_code' => '502', 'code' => 'GT', 'name' => 'Guatemala']);
		Country::create(['calling_code' => '44', 'code' => 'GG', 'name' => 'Guernsey']);
		Country::create(['calling_code' => '224', 'code' => 'GN', 'name' => 'Guinea']);
		Country::create(['calling_code' => '245', 'code' => 'GW', 'name' => 'Guinea-Bissau']);
		Country::create(['calling_code' => '592', 'code' => 'GY', 'name' => 'Guyana']);
		Country::create(['calling_code' => '509', 'code' => 'HT', 'name' => 'Haiti']);
		Country::create(['calling_code' => '3906', 'code' => 'VA', 'name' => 'Holy See (Vatican City State)']);
		Country::create(['calling_code' => '504', 'code' => 'HN', 'name' => 'Honduras']);
		Country::create(['calling_code' => '852', 'code' => 'HK', 'name' => 'Hong Kong']);
		Country::create(['calling_code' => '36', 'code' => 'HU', 'name' => 'Hungary']);
		Country::create(['calling_code' => '354', 'code' => 'IS', 'name' => 'Iceland']);
		Country::create(['calling_code' => '91', 'code' => 'IN', 'name' => 'India']);
		Country::create(['calling_code' => '62', 'code' => 'ID', 'name' => 'Indonesia']);
		Country::create(['calling_code' => '98', 'code' => 'IR', 'name' => 'Iran, Islamic Republic of']);
		Country::create(['calling_code' => '964', 'code' => 'IQ', 'name' => 'Iraq']);
		Country::create(['calling_code' => '353', 'code' => 'IE', 'name' => 'Ireland']);
		Country::create(['calling_code' => '44', 'code' => 'IM', 'name' => 'Isle of Man']);
		Country::create(['calling_code' => '972', 'code' => 'IL', 'name' => 'Israel']);
		Country::create(['calling_code' => '39', 'code' => 'IT', 'name' => 'Italy']);
		Country::create(['calling_code' => '1', 'code' => 'JM', 'name' => 'Jamaica']);
		Country::create(['calling_code' => '81', 'code' => 'JP', 'name' => 'Japan']);
		Country::create(['calling_code' => '44', 'code' => 'JE', 'name' => 'Jersey']);
		Country::create(['calling_code' => '962', 'code' => 'JO', 'name' => 'Jordan']);
		Country::create(['calling_code' => '7', 'code' => 'KZ', 'name' => 'Kazakhstan']);
		Country::create(['calling_code' => '254', 'code' => 'KE', 'name' => 'Kenya']);
		Country::create(['calling_code' => '686', 'code' => 'KI', 'name' => 'Kiribati']);
		Country::create(['calling_code' => '850', 'code' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of']);
		Country::create(['calling_code' => '82', 'code' => 'KR', 'name' => 'Korea, Republic of']);
		Country::create(['calling_code' => '965', 'code' => 'KW', 'name' => 'Kuwait']);
		Country::create(['calling_code' => '996', 'code' => 'KG', 'name' => 'Kyrgyzstan']);
		Country::create(['calling_code' => '856', 'code' => 'LA', 'name' => 'Lao People\'s Democratic Republic']);
		Country::create(['calling_code' => '371', 'code' => 'LV', 'name' => 'Latvia']);
		Country::create(['calling_code' => '961', 'code' => 'LB', 'name' => 'Lebanon']);
		Country::create(['calling_code' => '266', 'code' => 'LS', 'name' => 'Lesotho']);
		Country::create(['calling_code' => '231', 'code' => 'LR', 'name' => 'Liberia']);
		Country::create(['calling_code' => '218', 'code' => 'LY', 'name' => 'Libyan Arab Jamahiriya']);
		Country::create(['calling_code' => '423', 'code' => 'LI', 'name' => 'Liechtenstein']);
		Country::create(['calling_code' => '370', 'code' => 'LT', 'name' => 'Lithuania']);
		Country::create(['calling_code' => '352', 'code' => 'LU', 'name' => 'Luxembourg']);
		Country::create(['calling_code' => '853', 'code' => 'MO', 'name' => 'Macao']);
		Country::create(['calling_code' => '389', 'code' => 'MK', 'name' => 'Macedonia, the former Yugoslav Republic of']);
		Country::create(['calling_code' => '261', 'code' => 'MG', 'name' => 'Madagascar']);
		Country::create(['calling_code' => '265', 'code' => 'MW', 'name' => 'Malawi']);
		Country::create(['calling_code' => '60', 'code' => 'MY', 'name' => 'Malaysia']);
		Country::create(['calling_code' => '960', 'code' => 'MV', 'name' => 'Maldives']);
		Country::create(['calling_code' => '223', 'code' => 'ML', 'name' => 'Mali']);
		Country::create(['calling_code' => '356', 'code' => 'MT', 'name' => 'Malta']);
		Country::create(['calling_code' => '692', 'code' => 'MH', 'name' => 'Marshall Islands']);
		Country::create(['calling_code' => '596', 'code' => 'MQ', 'name' => 'Martinique']);
		Country::create(['calling_code' => '222', 'code' => 'MR', 'name' => 'Mauritania']);
		Country::create(['calling_code' => '230', 'code' => 'MU', 'name' => 'Mauritius']);
		Country::create(['calling_code' => '262', 'code' => 'YT', 'name' => 'Mayotte']);
		Country::create(['calling_code' => '52', 'code' => 'MX', 'name' => 'Mexico']);
		Country::create(['calling_code' => '691', 'code' => 'FM', 'name' => 'Micronesia, Federated States of']);
		Country::create(['calling_code' => '373', 'code' => 'MD', 'name' => 'Moldova, Republic of']);
		Country::create(['calling_code' => '377', 'code' => 'MC', 'name' => 'Monaco']);
		Country::create(['calling_code' => '976', 'code' => 'MN', 'name' => 'Mongolia']);
		Country::create(['calling_code' => '382', 'code' => 'ME', 'name' => 'Montenegro']);
		Country::create(['calling_code' => '1', 'code' => 'MS', 'name' => 'Montserrat']);
		Country::create(['calling_code' => '212', 'code' => 'MA', 'name' => 'Morocco']);
		Country::create(['calling_code' => '258', 'code' => 'MZ', 'name' => 'Mozambique']);
		Country::create(['calling_code' => '94', 'code' => 'MM', 'name' => 'Myanmar']);
		Country::create(['calling_code' => '264', 'code' => 'NA', 'name' => 'Namibia']);
		Country::create(['calling_code' => '674', 'code' => 'NR', 'name' => 'Nauru']);
		Country::create(['calling_code' => '977', 'code' => 'NP', 'name' => 'Nepal']);
		Country::create(['calling_code' => '31', 'code' => 'NL', 'name' => 'Netherlands']);
		Country::create(['calling_code' => '599', 'code' => 'AN', 'name' => 'Netherlands Antilles']);
		Country::create(['calling_code' => '687', 'code' => 'NC', 'name' => 'New Caledonia']);
		Country::create(['calling_code' => '64', 'code' => 'NZ', 'name' => 'New Zealand']);
		Country::create(['calling_code' => '505', 'code' => 'NI', 'name' => 'Nicaragua']);
		Country::create(['calling_code' => '227', 'code' => 'NE', 'name' => 'Niger']);
		Country::create(['calling_code' => '234', 'code' => 'NG', 'name' => 'Nigeria']);
		Country::create(['calling_code' => '683', 'code' => 'NU', 'name' => 'Niue']);
		Country::create(['calling_code' => '672', 'code' => 'NF', 'name' => 'Norfolk Island']);
		Country::create(['calling_code' => '1', 'code' => 'MP', 'name' => 'Northern Mariana Islands']);
		Country::create(['calling_code' => '47', 'code' => 'NO', 'name' => 'Norway']);
		Country::create(['calling_code' => '968', 'code' => 'OM', 'name' => 'Oman']);
		Country::create(['calling_code' => '92', 'code' => 'PK', 'name' => 'Pakistan']);
		Country::create(['calling_code' => '680', 'code' => 'PW', 'name' => 'Palau']);
		Country::create(['calling_code' => '970', 'code' => 'PS', 'name' => 'Palestinian Territory, Occupied']);
		Country::create(['calling_code' => '507', 'code' => 'PA', 'name' => 'Panama']);
		Country::create(['calling_code' => '675', 'code' => 'PG', 'name' => 'Papua New Guinea']);
		Country::create(['calling_code' => '595', 'code' => 'PY', 'name' => 'Paraguay']);
		Country::create(['calling_code' => '51', 'code' => 'PE', 'name' => 'Peru']);
		Country::create(['calling_code' => '63', 'code' => 'PH', 'name' => 'Philippines']);
		Country::create(['calling_code' => '649', 'code' => 'PN', 'name' => 'Pitcairn']);
		Country::create(['calling_code' => '48', 'code' => 'PL', 'name' => 'Poland']);
		Country::create(['calling_code' => '351', 'code' => 'PT', 'name' => 'Portugal']);
		Country::create(['calling_code' => '1', 'code' => 'PR', 'name' => 'Puerto Rico']);
		Country::create(['calling_code' => '974', 'code' => 'QA', 'name' => 'Qatar']);
		Country::create(['calling_code' => '262', 'code' => 'RE', 'name' => 'Réunion']);
		Country::create(['calling_code' => '40', 'code' => 'RO', 'name' => 'Romania']);
		Country::create(['calling_code' => '7', 'code' => 'RU', 'name' => 'Russian Federation']);
		Country::create(['calling_code' => '250', 'code' => 'RW', 'name' => 'Rwanda']);
		Country::create(['calling_code' => '590', 'code' => 'BL', 'name' => 'Saint Barthélemy']);
		Country::create(['calling_code' => '290', 'code' => 'SH', 'name' => 'Saint Helena, Ascension and Tristan da Cunha']);
		Country::create(['calling_code' => '1', 'code' => 'KN', 'name' => 'Saint Kitts and Nevis']);
		Country::create(['calling_code' => '1', 'code' => 'LC', 'name' => 'Saint Lucia']);
		Country::create(['calling_code' => '1', 'code' => 'MF', 'name' => 'Saint Martin (French part)']);
		Country::create(['calling_code' => '508', 'code' => 'PM', 'name' => 'Saint Pierre and Miquelon']);
		Country::create(['calling_code' => '1', 'code' => 'VC', 'name' => 'Saint Vincent and the Grenadines']);
		Country::create(['calling_code' => '685', 'code' => 'WS', 'name' => 'Samoa']);
		Country::create(['calling_code' => '378', 'code' => 'SM', 'name' => 'San Marino']);
		Country::create(['calling_code' => '239', 'code' => 'ST', 'name' => 'Sao Tome and Principe']);
		Country::create(['calling_code' => '966', 'code' => 'SA', 'name' => 'Saudi Arabia']);
		Country::create(['calling_code' => '221', 'code' => 'SN', 'name' => 'Senegal']);
		Country::create(['calling_code' => '382', 'code' => 'RS', 'name' => 'Serbia']);
		Country::create(['calling_code' => '248', 'code' => 'SC', 'name' => 'Seychelles']);
		Country::create(['calling_code' => '232', 'code' => 'SL', 'name' => 'Sierra Leone']);
		Country::create(['calling_code' => '65', 'code' => 'SG', 'name' => 'Singapore']);
		Country::create(['calling_code' => '421', 'code' => 'SK', 'name' => 'Slovakia']);
		Country::create(['calling_code' => '386', 'code' => 'SI', 'name' => 'Slovenia']);
		Country::create(['calling_code' => '677', 'code' => 'SB', 'name' => 'Solomon Islands']);
		Country::create(['calling_code' => '252', 'code' => 'SO', 'name' => 'Somalia']);
		Country::create(['calling_code' => '27', 'code' => 'ZA', 'name' => 'South Africa']);
		Country::create(['calling_code' => '34', 'code' => 'ES', 'name' => 'Spain']);
		Country::create(['calling_code' => '94', 'code' => 'LK', 'name' => 'Sri Lanka']);
		Country::create(['calling_code' => '249', 'code' => 'SD', 'name' => 'Sudan']);
		Country::create(['calling_code' => '597', 'code' => 'SR', 'name' => 'Suriname']);
		Country::create(['calling_code' => 'x', 'code' => 'SJ', 'name' => 'Svalbard and Jan Mayen']);
		Country::create(['calling_code' => '268', 'code' => 'SZ', 'name' => 'Swaziland']);
		Country::create(['calling_code' => '46', 'code' => 'SE', 'name' => 'Sweden']);
		Country::create(['calling_code' => '41', 'code' => 'CH', 'name' => 'Switzerland']);
		Country::create(['calling_code' => '963', 'code' => 'SY', 'name' => 'Syrian Arab Republic']);
		Country::create(['calling_code' => '886', 'code' => 'TW', 'name' => 'Taiwan']);
		Country::create(['calling_code' => '992', 'code' => 'TJ', 'name' => 'Tajikistan']);
		Country::create(['calling_code' => '255', 'code' => 'TZ', 'name' => 'Tanzania, United Republic of']);
		Country::create(['calling_code' => '66', 'code' => 'TH', 'name' => 'Thailand']);
		Country::create(['calling_code' => '670', 'code' => 'TL', 'name' => 'Timor-Leste']);
		Country::create(['calling_code' => '228', 'code' => 'TG', 'name' => 'Togo']);
		Country::create(['calling_code' => '690', 'code' => 'TK', 'name' => 'Tokelau']);
		Country::create(['calling_code' => '676', 'code' => 'TO', 'name' => 'Tonga']);
		Country::create(['calling_code' => '1', 'code' => 'TT', 'name' => 'Trinidad and Tobago']);
		Country::create(['calling_code' => '216', 'code' => 'TN', 'name' => 'Tunisia']);
		Country::create(['calling_code' => '90', 'code' => 'TR', 'name' => 'Turkey']);
		Country::create(['calling_code' => '993', 'code' => 'TM', 'name' => 'Turkmenistan']);
		Country::create(['calling_code' => '1', 'code' => 'TC', 'name' => 'Turks and Caicos Islands']);
		Country::create(['calling_code' => '688', 'code' => 'TV', 'name' => 'Tuvalu']);
		Country::create(['calling_code' => '256', 'code' => 'UG', 'name' => 'Uganda']);
		Country::create(['calling_code' => '380', 'code' => 'UA', 'name' => 'Ukraine']);
		Country::create(['calling_code' => '971', 'code' => 'AE', 'name' => 'United Arab Emirates']);
		Country::create(['calling_code' => '44', 'code' => 'GB', 'name' => 'United Kingdom']);
		Country::create(['calling_code' => '1', 'code' => 'US', 'name' => 'United States']);
		Country::create(['calling_code' => '598', 'code' => 'UY', 'name' => 'Uruguay']);
		Country::create(['calling_code' => '998', 'code' => 'UZ', 'name' => 'Uzbekistan']);
		Country::create(['calling_code' => '678', 'code' => 'VU', 'name' => 'Vanuatu']);
		Country::create(['calling_code' => '58', 'code' => 'VE', 'name' => 'Venezuela, Bolivarian Republic of']);
		Country::create(['calling_code' => '84', 'code' => 'VN', 'name' => 'Viet Nam']);
		Country::create(['calling_code' => '1', 'code' => 'VG', 'name' => 'Virgin Islands, British']);
		Country::create(['calling_code' => '1', 'code' => 'VI', 'name' => 'Virgin Islands, U.S.']);
		Country::create(['calling_code' => '681', 'code' => 'WF', 'name' => 'Wallis and Futuna']);
		Country::create(['calling_code' => 'x', 'code' => 'EH', 'name' => 'Western Sahara']);
		Country::create(['calling_code' => '967', 'code' => 'YE', 'name' => 'Yemen']);
		Country::create(['calling_code' => '260', 'code' => 'ZM', 'name' => 'Zambia']);
		Country::create(['calling_code' => '263', 'code' => 'ZW', 'name' => 'Zimbabwe']);

    }

}